### ISSUE TITLE
SDK requires app to use a theme with an ActionBar

### ISSUE THREAD

**Issue by JoelReeves** [zendesk/sdk_demo_app_android#2]
In trying to move away from the ActionBar to the Toolbar class, I recently discovered the following issue. If I set my app's theme to Theme.AppCompat.Light.NoActionBar and then in my ActionBarActivity's onCreate method I declare the Toolbar as the Actionbar via the setSupportActionBar method, the app will crash when trying to call this line:
startActivity(new Intent(MainActivity.this, ContactZendeskActivity.class)); 
(NPE comes from within ContactZendeskActivity's onCreate method)

However if I change my theme to Theme.AppCompat.Light then I can call the line fine.

**Comment by norman-kapschefsky** [comment]
Hi, you are totally right. I run into the same problem. Our app uses the Toolbar and it crashes with 

<code>java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
            at com.zendesk.sdk.feedback.ui.ContactZendeskActivity.onCreate(Unknown Source)</code>

because the sdk relies on it. But due to the fact that the theme is overwritten in manifest this can happen. I cant understand why its not fixed yet.

**Comment by JoelReeves** [comment]
Thanks for the info. I ended up not using the startActivity method to start ContactZendeskActivity. Instead I used the RequestProvider method of submit a ticket via a form in mp app.

**Comment by norman-kapschefsky** [comment]
Jeah, the approach I mentioned above is not good at all^^. I had problems with merging the Zendesk SDK  manifest into the project. Even with <code>tools:replace="android:theme"</code> it doesnt worked. But I added to each of my activites my own theme and deleted the property <code>android:theme</code> from the applicaton tag: After that merging was possible and no further declaration due to zendesk sdk were needed.

**Comment by smaspe** [comment]
@norman-kapschefsky I used `tools:node="replace"` to overcome the `replace` issues in the `application` node. It may work for you too.

**Comment by baz8080** [comment]
Hi, just closing the loop on this one. We're aware of our dependency on `ActionBar` for some activities and we provide an alternative with fragments and [Providers](https://developer.zendesk.com/embeddables/docs/android/providers).  I'm closing this issue for now.
